import os

SEPARATOR = os.path.sep

NUMBER_OF_PROCESSORS = 10
IS_DATA_CLEANED = False

# AIRPORTS = [
#     "KATL",
#     "KCLT",
#     "KDEN",
#     "KDFW",
#     "KJFK",
#     "KMEM",
#     "KMIA",
#     "KORD",
#     "KPHX",
#     "KSEA"
# ]


AIRPORTS = [
    "KCLT"
]



FILE_NAME_CONFIG = "config"
FILE_NAME_ETD = "etd"
FILE_NAME_FIRST_POSITION = "first_position"
FILE_NAME_LAMP = "lamp"
FILE_NAME_MFS = "mfs"
FILE_NAME_RUNWAYS = "runways"
FILE_NAME_STANDTIMES = "standtimes"
FILE_NAME_TBFM = "tbfm"
FILE_NAME_TFM = "tfm"
FILE_NAME_RESULTS = "results"
FILE_NAME_LABELS = "train_labels_"

COLUMN_NAME_TIMESTAMP = 'timestamp'

RUNWAYS_COLUMN_ARRIVAL_RUNWAYS = "arrival_runways"

MODEL_PATH = f"data{SEPARATOR}model{SEPARATOR}"

#TRAIN_PATH = f"data{SEPARATOR}train{SEPARATOR}"
TRAIN_PATH = f"data{SEPARATOR}small_data{SEPARATOR}"

FLIGHT_ID = "gufi"

CLOUD_CATEGORY_PREFIX = 'cl_'
CLOUD_CATEGORY_BK = "BK"
CLOUD_CATEGORY_CL = "CL"
CLOUD_CATEGORY_FEW = "FW"
CLOUD_CATEGORY_OV = "OV"
CLOUD_CATEGORY_SC = "SC"

LIGHTNING_PROB_CATEGORY_PREFIX = 'lp_'
LIGHTNING_PROB_CATEGORY_N = "N"
LIGHTNING_PROB_CATEGORY_L = "L"
LIGHTNING_PROB_CATEGORY_M = "M"
LIGHTNING_PROB_CATEGORY_H = "H"

MFS_COLUMN_FLIGHT_ID = FLIGHT_ID
MFS_COLUMN_AIRCRAFT_ENGINE_CLASS = "aircraft_engine_class"
MFS_COLUMN_AIRCRAFT_TYPE = "aircraft_type"
MFS_COLUMN_MAJOR_CARRIER = "major_carrier"
MFS_COLUMN_FLIGHT_TYPE = "flight_type"
MFS_COLUMN_IS_DEPARTURE = "isdeparture"

LAMP_COLUMN_TIMESTAMP = COLUMN_NAME_TIMESTAMP
LAMP_COLUMN_FORECAST_TIMESTAMP = 'forecast_timestamp'
LAMP_COLUMN_TEMPERATURE = 'temperature'
LAMP_COLUMN_WIND_DIRECTION = 'wind_direction'
LAMP_COLUMN_WIND_SPEED = 'wind_speed'
LAMP_COLUMN_WIND_GUST = 'wind_gust'
LAMP_COLUMN_CLOUD_CEILING = 'cloud_ceiling'
LAMP_COLUMN_VISIBILITY = 'visibility'
LAMP_COLUMN_CLOUD = 'cloud'
LAMP_COLUMN_LIGHTNING_PROB = 'lightning_prob'
LAMP_COLUMN_PRECIP = 'precip'

RUNWAYS_COLUMN_FLIGHT_ID = FLIGHT_ID
RUNWAYS_COLUMN_TIMESTAMP = COLUMN_NAME_TIMESTAMP
RUNWAYS_COLUMN_DEPARTURE_RUNWAY_ACTUAL = 'departure_runway_actual'
RUNWAYS_COLUMN_DEPARTURE_RUNWAY_ACTUAL_TIME = 'departure_runway_actual_time'
RUNWAYS_COLUMN_ARRIVAL_RUNWAY_ACTUAL = 'arrival_runway_actual'
RUNWAYS_COLUMN_ARRIVAL_RUNWAY_ACTUAL_TIME = 'arrival_runway_actual_time'

STANDTIMES_COLUMN_FLIGHT_ID = FLIGHT_ID
STANDTIMES_COLUMN_TIMESTAMP = COLUMN_NAME_TIMESTAMP
STANDTIMES_COLUMN_ARRIVAL_STAND_ACTUAL_TIME = 'arrival_stand_actual_time'
STANDTIMES_COLUMN_DEPARTURE_STAND_ACTUAL_TIME = 'departure_stand_actual_time'

ETD_COLUMN_FLIGHT_ID = FLIGHT_ID
ETD_COLUMN_TIMESTAMP = COLUMN_NAME_TIMESTAMP
ETD_COLUMN_DEPARTURE_RUNWAY_ESTIMATED_TIME = 'departure_runway_estimated_time'

TBFM_COLUMN_FLIGHT_ID = FLIGHT_ID
TBFM_COLUMN_TIMESTAMP = COLUMN_NAME_TIMESTAMP
TBFM_COLUMN_SCHEDULED_RUNWAY_ESTIMATED_TIME = 'scheduled_runway_estimated_time'

TFM_COLUMN_FLIGHT_ID = FLIGHT_ID
TFM_COLUMN_TIMESTAMP = COLUMN_NAME_TIMESTAMP
TFM_COLUMN_ARRIVAL_RUNWAY_ESTIMATED_TIME = 'arrival_runway_estimated_time'

CONFIG_COLUMN_TIMESTAMP = COLUMN_NAME_TIMESTAMP
CONFIG_COLUMN_START_TIME = 'start_time'
CONFIG_COLUMN_DEPARTURE_RUNWAYS = 'departure_runways'
CONFIG_COLUMN_ARRIVAL_RUNWAYS = 'arrival_runways'

SUBMISSION_FORMAT_FLIGHT_ID = FLIGHT_ID
SUBMISSION_FORMAT_TIMESTAMP = COLUMN_NAME_TIMESTAMP
SUBMISSION_FORMAT_AIRPORT = 'airport'
SUBMISSION_FORMAT_MINUTES_UNTIL_PUSHBACK = 'minutes_until_pushback'

FEATURE_COLUMN_WEIGHTED_MEAN_ARRIVAL_TO_GATE = "WEIGHTED_MEAN_ARRIVAL_TO_GATE"
